Fix compilation error in tutorials for linux
:Release Notes:
GLTF library contains implicit dependency from openmp.
Latest gcc version doesn't include openmp by default, so it is requried to bypass
-fopenmp flag to linkage

:Detailed Notes:

Fix error:
RadeonProRender/binUbuntu18/libProRenderGLTF.so: undefined reference to `omp_get_thread_num'
RadeonProRender/binUbuntu18/libProRenderGLTF.so: undefined reference to `omp_get_num_threads'
RadeonProRender/binUbuntu18/libProRenderGLTF.so: undefined reference to `omp_get_thread_num'
RadeonProRender/binUbuntu18/libProRenderGLTF.so: undefined reference to `omp_get_num_threads'
RadeonProRender/binUbuntu18/libProRenderGLTF.so: undefined reference to `GOMP_parallel'
RadeonProRender/binUbuntu18/libProRenderGLTF.so: undefined reference to `GOMP_parallel'

:Testing Performed:
Compilation and run at gentoo linux

:QA Notes:

:Issues Addressed:

Signed-off-by: Maksym Sditanov <msditanov@200volts.com>